// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-mRSEZUNabwhflulnIjJunYXCATbRjYU',
    appId: '1:685136842861:web:e3909c417597d05b27af64',
    messagingSenderId: '685136842861',
    projectId: 'logindemo-7ed5f',
    authDomain: 'logindemo-7ed5f.firebaseapp.com',
    storageBucket: 'logindemo-7ed5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS2-MROUsneNUijDZqnmUClLpV0vK_ZLU',
    appId: '1:685136842861:android:6179897765fb057d27af64',
    messagingSenderId: '685136842861',
    projectId: 'logindemo-7ed5f',
    storageBucket: 'logindemo-7ed5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbCTKZ_CMSBqgG44Cmwnw5mOomI5h6AE',
    appId: '1:685136842861:ios:70bac8ad5e6c7fce27af64',
    messagingSenderId: '685136842861',
    projectId: 'logindemo-7ed5f',
    storageBucket: 'logindemo-7ed5f.appspot.com',
    iosClientId: '685136842861-9mu6rbduahgo8rvab3kh5u7rb9r50d0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbCTKZ_CMSBqgG44Cmwnw5mOomI5h6AE',
    appId: '1:685136842861:ios:70bac8ad5e6c7fce27af64',
    messagingSenderId: '685136842861',
    projectId: 'logindemo-7ed5f',
    storageBucket: 'logindemo-7ed5f.appspot.com',
    iosClientId: '685136842861-9mu6rbduahgo8rvab3kh5u7rb9r50d0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoLogin',
  );
}
